#include "smmap/diminishing_rigidity_model.h"

#include <stdexcept>
#include <limits>

#include <ros/ros.h>

using namespace smmap;

////////////////////////////////////////////////////////////////////////////////
// Constructors and Destructor
////////////////////////////////////////////////////////////////////////////////

DiminishingRigidityModel::DiminishingRigidityModel(
        const ObjectPointSet& object_initial_configuration, double k )
    : DiminishingRigidityModel( object_initial_configuration, k, k )
{}

DiminishingRigidityModel::DiminishingRigidityModel(
        const ObjectPointSet& object_initial_configuration, double k_translation, double k_rotation )
    : object_initial_configuration_( object_initial_configuration )
    , k_translation_( k_translation )
    , k_rotation_( k_rotation )
{
    if ( k_translation <= 0 )
    {
        throw new std::invalid_argument("k_translation must be greater than 0");
    }
    if ( k_rotation <= 0 )
    {
        throw new std::invalid_argument("k_rotation must be greater than 0");
    }

    computeObjectNodeDistanceMatrix();
}

////////////////////////////////////////////////////////////////////////////////
// Constructor helpers
////////////////////////////////////////////////////////////////////////////////

void DiminishingRigidityModel::computeObjectNodeDistanceMatrix()
{
    if ( object_initial_node_distance_.size() == 0 )
    {
        ROS_INFO( "Computing object initial distance matrix" );

        const size_t num_nodes = object_initial_configuration_.cols();
        object_initial_node_distance_.resize( num_nodes, num_nodes );
        for ( size_t i = 0; i < num_nodes; i++ )
        {
            for ( size_t j = i; j < num_nodes; j++ )
            {
                object_initial_node_distance_( i, j ) =
                    ( object_initial_configuration_.block< 3, 1>( 0, i )
                    - object_initial_configuration_.block< 3, 1>( 0, j ) ).norm();
                object_initial_node_distance_( j, i ) = object_initial_node_distance_( i, j );
            }
        }
    }
}

////////////////////////////////////////////////////////////////////////////////
// Virtual function overrides
////////////////////////////////////////////////////////////////////////////////

void DiminishingRigidityModel::doUpdateModel(
        const std::vector< std::vector< size_t > >& gripper_node_indices,
        const std::vector< GripperTrajectory >& gripper_trajectories,
        const std::vector< kinematics::VectorVector6d >& gripper_velocities,
        const ObjectTrajectory& object_trajectory,
        const kinematics::VectorMatrix3Xd& object_velocities )
{
}

ObjectTrajectory DiminishingRigidityModel::doGetPrediction(
        const ObjectPointSet& object_configuration,
        const std::vector< GripperTrajectory>& gripper_trajectories,
        const std::vector< kinematics::VectorVector6d >& gripper_velocities ) const
{
    assert( gripper_trajectories.size() > 0 );
    assert( gripper_velocities.size() == gripper_trajectories.size() );

    ObjectTrajectory object_traj( gripper_trajectories[0].size(), object_configuration );
    return object_traj;
}

void DiminishingRigidityModel::doPerturbModel( std::mt19937_64& generator )
{
    k_translation_ += perturbation_distribution( generator );
    k_rotation_ += perturbation_distribution( generator );

    if ( k_translation_ <= 0 )
    {
        k_translation_ = std::numeric_limits< double >::epsilon();
    }
    if ( k_rotation_ <= 0 )
    {
        k_rotation_ = std::numeric_limits< double >::epsilon();
    }
}

void DiminishingRigidityModel::computeJacobian()
{
}

////////////////////////////////////////////////////////////////////////////////
// Static member initialization
////////////////////////////////////////////////////////////////////////////////

/// TODO: remove this magic number for the noise generated by this distribution
std::normal_distribution< double > DiminishingRigidityModel::perturbation_distribution =
    std::normal_distribution< double >( 0, 0.1 );

Eigen::MatrixXd DiminishingRigidityModel::object_initial_node_distance_;
